config/routes.rb
Rails.application.routes.draw do

  get 'pledges/create'
  get 'messages/create'

  devise_for :users do

  end

  resources :users, except: :show do

  end

  get 'profile/projects', to: 'projects#my'
  get 'profile/messages', to: 'messages#my'

  post 'profile/avatar', to: 'api/users#upload_avatar'

  get 'profile', to: 'users#show'
  get 'profile/edit', to: 'users#edit'
  get 'profile/:id', to: 'users#show', as: 'user_profile'
  put 'profile', to: 'users#update_profile'

  resources :messages do

  end

  get 'discover', to: 'discover#index'
  get 'discover/categories/:id', to: 'discover#category_projects', as: 'discover_category'

  resources :projects do

    collection do
      get 'create'
      get 'search'
    end

    resources :posts do

    end

    resources :rewards do

    end

    resources :pledges do

    end

    resources :comments do

    end

    member do

    end
  end

  get 'home/index'
  get 'home/about'
  # You can have the root of your site routed with "root"
  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  namespace :api do
    resources :projects do

      member do
        post :avatar, to: 'projects#upload_avatar', as: 'avatar'
      end

      resources :posts do

      end

      resources :rewards do

      end
    end

    post 'projects/:id' => 'projects#execute'

    resources :users do

    end


  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId

  mount_uploader :image, ProjectImageUploader

  enum duration_type: { :duration => 0, :deadline => 1 }

  before_validation(on: [:create, :update]) do
    self.title = self.title.strip if attribute_present?("title")
    self.short_description = self.short_description.strip if attribute_present?("short_description")

    if attribute_present?("deadline")
      self.deadline = self.deadline.change(hour: 23, min: 59, sec: 59)
    end

  end

  friendly_id :title, :use => :slugged

  belongs_to :user, :class_name => "User", :foreign_key => :creator_id, :autosave => false
  belongs_to :category, :class_name => "Category", :foreign_key => :category_id

  has_many :comments
  has_many :pledges
  has_many :posts
  has_many :rewards

  validates_presence_of :title, :location, :slug
  validates_length_of :short_description, maximum: 200
  validates_numericality_of :funding_goal, minimum: 0

  # Overrides
  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :vietnamese).to_s
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def unsuccessful?
    ended? && total_pledge_amount < funding_goal
  end

  def ended?
    launched? && !stopped? && deadline <= Time.zone.now
  end

  def funding?
    launched? && !stopped? && deadline > Time.zone.now
  end

  def total_pledge_amount
    pledges.sum(:pledge_amount)
  end

  def remaining_days
    [(deadline - Time.zone.now).to_i / 1.day, 0].max
  end

  def has_video?
    return false
  end

  def launched?
    launched_at != nil
  end

  def stopped?
    stopped_at != nil
  end

  def deleted?
    deleted_at != nil
  end

  def initiating?
    !launched? && !stopped? && !deleted?
  end





end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController

  skip_before_filter :verify_authenticity_token, :only => [:update, :execute, :upload_avatar]

  respond_to :json, :except => [:upload_avatar]
  respond_to :html, :only => [:upload_avatar]

  def index
    projects = Project.all
    respond_with projects
  end

  def show
    project = Project.find(params[:id])
    respond_with project
  end

  def update
    project = Project.find(params[:id])
    user = current_user

    params = project.launched ? launched_project_params : project_params

    project.assign_attributes(params)
    user.assign_attributes(project_user_params[:user])

    begin
      project.transaction do
        project.save!
        user.save!
      end
      render json: {:project => project.as_json.merge({ :user => user.as_json(:only => [:email, :id, :name, :biology, :location, :website]).merge({:image_url => user.avatar_url(:standard)}),})}
    rescue ActiveRecord::RecordInvalid => exception
      render json: {:project => project.as_json.merge({ :user => user.as_json(:only => [:email, :id, :name, :biology, :location, :website]).merge({:image_url => user.avatar_url(:standard), :errors => user.errors}),
                                                        :errors => project.errors })}, :status => 200
    end
  end

  def execute
    project = Project.find(params[:id])
    operation = params[:operation]

    case operation
      when "launch"
        launch_project(project)
      when "stop"
        stop_project(project)
      else

    end
  end

  def upload_avatar
    project = Project.find(params[:id])
    
    if project.update_attributes(:image => params[:project][:image])
      render json: { :image_url => project.image_url(:medium) }
    else
      render json: { :errors => project.errors }
    end
  end

  protected
  def launch_project(project)

    if project.deleted? || project.launched? || project.stopped?
      render json: {:project => project}
    end

    current_time = Time.zone.now

    if project.duration_type == "duration"
      duration = project.duration
      deadline = current_time + duration.days
    else
      deadline = project.deadline
      duration = (deadline - current_time).to_i / 1.day
    end

    deadline = deadline.change(hour: 23, min: 59, sec: 59)

    if project.update_attributes(
        :launched => true,
        :launched_at => current_time,
        :deadline => deadline,
        :duration => duration
    )
      render json: { :project => project }
    else
      render json: { :project => project.as_json.merge({:errors => project.errors}) }
    end
  end

  def stop_project(project)

  end

  private
  def project_params
    json_params = ActionController::Parameters.new(JSON.parse(request.body.read))
    json_params.require(:project).permit(:title, :location, :category_id, :short_description, :funding_goal, :duration_type, :duration, :deadline, :image)
  end

  def project_user_params
    json_params = ActionController::Parameters.new(JSON.parse(request.body.read))
    json_params.require(:project).permit(:user => [:name, :biology, :location, :website])
  end

  def launched_project_params
    json_params = ActionController::Parameters.new(JSON.parse(request.body.read))
    json_params.require(:project).permit(:title, :location, :category_id, :short_description, :image, :user)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show, :new]
  skip_before_filter :verify_authenticity_token, :only => [:upload_image]


  def index
    @projects = Project.where(launched_at: nil, deleted_at: nil, stopped_at: nil)


  end

  def about

  end

  def my
    @projects = Project.where(user: current_user)
  end

  def search
    search_key = params[:search_key]

  end

  def show
    @project = Project.includes(:user).friendly.find(params[:id])

    if @project.deleted? || (!my_project?(@project) && @project.initiating?)
      redirect_to root_path

    else
      @pledges = @project.pledges

      render 'show'
    end

  end

  def share



  end

  def new
    @cities = City.all

    @categories = Category.all

    @project = Project.new()

  end

  #View to create a new projects
  def create
    project = Project.new(project_params)
    user = current_user
    project.creator_id = user.id
    project.funding_goal = 1000000
    project.duration = 10

    if project.save
      redirect_to edit_project_path(project.id)
    else
      @cities = City.all
      @categories = Category.all
      @project = project
      @project.category_id = params[:project][:category_id]
      @project.location = params[:project][:location]
      render 'new'
    end
  end

  #View to edit an existing projects
  def edit
    @cities = Rails.cache.fetch("cities/all", expires_in: 30.days) do
        City.all
    end

    project = Project.find(params[:id])

    if project.deleted? || !my_project?(project)
      redirect_to root_path
    end

    if project.duration_type == "duration"
      project.deadline = Time.zone.now
      project.duration = project.duration || 1
    else
      project.duration = 0
    end

    gon.project = project.as_json.merge(
        {
            :image_url => project.image_url(:medium),
            :project_image_upload_url => avatar_api_project_path(project.id),
            :deadline => project.deadline.strftime("%d-%m-%Y"),
            :user => project.user.as_json(:only => [:email, :id, :name, :biology, :location, :website]).merge(
                {
                    :image_url => project.user.avatar_url(:standard),
                    :user_avatar_upload_url => "/profile/avatar"
                }),
            :rewards => Rails.cache.fetch("projects/#{project.id}/rewards/all", expires_in: 30.days) do
              Reward.where("project_id = :project_id", { project_id: project.id }).map { |reward| reward.as_json }
            end,
            :posts => Rails.cache.fetch("projects/#{project.id}/posts/all", expires_in: 30.days) do
              Post.where("project_id = :project_id", { project_id: project.id }).map { |post| post.as_json.merge({:image_url => post.image_url(:medium)}) }
            end
        }
    )

    @project = project
  end

  def stop_project

    project = Project.find(params[:id])

    render json: {:success => false} if project.deleted?
    render json: {:success => false} if !project.launched?
    render json: {:success => false} if project.stopped?

    if project.update_attributes(:stopped_at => Time.zone.now)
      render json: {:success => true}
    else
      render json: {:success => false, :errors => project.errors}
    end

  end

  private
    def my_project?(project)
      return current_user && project.creator_id == current_user.id
    end

    def project_params
      params.require(:project).permit(:title, :location, :category_id, :short_description, :funding_goal, :duration_type, :duration, :deadline)
    end

    def launched_project_params
      params.require(:project).permit(:title, :location, :category_id, :short_description)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def cache_key_for_project(project)
    "projects/#{project.id}-#{project.updated_at}"
  end

  def cache_key_for_project_posts(project)
    "projects/#{project.id}/posts/all"
  end

  def cache_key_for_project_rewards(project)
    "projects/#{project.id}/rewards/all"
  end

end

app/views/projects/shared/_edit_about_you.html.erb
    <div>
  <div class="section-guide">
    <h2>Thông tin cá nhân</h2>

    <p>
      Một trong những mục tiêu quan trọng của bất kỳ người huy động vốn nào là giành được niềm tin từ những khác. Hãy kể
      cho mọi người biết bạn là ai.
    </p>

    <p>
      Chúng tôi khuyến khích bạn liên kết tài khoàn VnStarter với tài khoản trên các mạng xã hội. Đó là cách nhanh nhất
      để người khác có thể tìm hiểu về bạn
    </p>
  </div>

  <%= form_for :user, url: '/profile', method: :put do |f| %>
      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <label>Ảnh cá nhân</label>
        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <ng-attachment-uploader
          auto-upload="true"
          name="user[avatar]"
          element-css-class="profile-photo"
          upload-url="{{project.user.userAvatarUploadUrl}}"
          default-image-url="project.user.imageUrl"></ng-attachment-uploader>
        </div>
      </div>

      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <label>Họ và tên</label>
        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <input type="text" name="name" ng-model="project.user.name" class="form-control" />
        </div>
      </div>

      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <label>Đôi điều về bản thân</label>
        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <div class="limit-characters">
            <textarea ng-model="project.user.biology" ng-trim="false" class="form-control" maxlength="{{userBiologyMaxLength}}" rows="5"></textarea>
            <p ng-bind="userBiologyMaxLength - project.user.biology.length + '/' + userBiologyMaxLength"></p>
          </div>
        </div>
      </div>

      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <%= f.label "Địa chỉ" %>
        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <select name="location" ng-model="project.user.location" class="form-control">
            <option ng-repeat="city in cities" value="{{city}}" ng-bind="'{{city}}'" ng-selected="project.user.location == city"></option>
          </select>
        </div>
      </div>

      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <label>Website</label>
        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <%= f.text_field :website, value: current_user.website, class: 'form-control' %>
        </div>
      </div>

      <div class="buttons-container text-right">
        <button type="button" class="btn btn-green" ng-click="saveProject()">Lưu thay đổi</button>
      </div>

  <% end %>
</div>

app/views/projects/shared/_edit_accounts.html.erb
<div class="row">
  <div class="col-xs-9 col-sm-9 col-md-8 col-lg-8">

    <div class="row">


      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          Email
        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <%= text_field_tag '', current_user.email, readonly: true, class: "form-control" %>
          <br>
          <span><button type="button" class="btn btn-primary">Gửi email xác nhận</button></span>
        </div>
      </div>

      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          Số điện thoại
        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <input type="text" name="" id="input" class="form-control" value="" required="required" pattern="" title="">
          <br>
          <span><button type="button" class="btn btn-primary">Gửi tin nhắn xác nhận
          </button></span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/shared/_edit_basic.html.erb
<div>
  <div class="section-guide">
    <h2>Thông tin cơ bản</h2>

    <p>
      Hãy tạo những ấn tượng đầu tiên. Giới thiệu về mục tiêu của dự án, điều gì làm dự án của bạn nổi bật và khiến cho
      mọi người muốn tìm hiểu nhiều hơn.
    </p>
  </div>

  <%= form_for :project, url: project_path(@project.id), method: :put do |f| %>

      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <%= f.label t('project.edit.basic.project_image') %><br/>

        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <ng-attachment-uploader
              auto-upload="true"

              name="project[image]"
              upload-url="{{project.projectImageUploadUrl}}"
              default-image-url="project.imageUrl"
              choose-file-button-text="Choose files"
              upload-file-button-text="Upload files"></ng-attachment-uploader>

          <p class="help">
            Chọn một bức ảnh đẹp và có độ phân giải cao làm ảnh đại diện cho dự án của bạn
          </p>
        </div>
      </div>

      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <%= f.label t('project.edit.basic.project_title') %><br/>

        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <input type="text" name="title" ng-model="project.title" class="form-control"/>

          <p class="help">
            Tên dự án của bạn cần đơn giản, đặc trưng và dễ nhớ
          </p>
        </div>
      </div>

      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <%= f.label t('project.edit.basic.short_description') %>
        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <div class="limit-characters">
            <textarea ng-model="project.shortDescription" ng-trim="false" class="form-control" maxlength="{{projectShortDescriptionMaxLength}}" rows="5"></textarea>
            <p ng-bind="projectShortDescriptionMaxLength - project.shortDescription.length + '/' + projectShortDescriptionMaxLength"></p>
          </div>
        </div>
      </div>

      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <%= f.label t('project.edit.basic.category') %>
        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <select ng-model="project.categoryId" class="form-control">
            <option ng-repeat="category in categories" value="{{category.id}}" ng-bind="'{{category.name}}'" ng-selected="project.categoryId == category.id"></option>
          </select>

        </div>
      </div>

      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <%= f.label t('project.edit.basic.location') %>
        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <select name="location" ng-model="project.location" class="form-control">
            <option ng-repeat="city in cities" value="{{city}}" ng-bind="'{{city}}'" ng-selected="project.location == city"></option>
          </select>
        </div>
      </div>

      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <%= f.label t('project.edit.basic.duration') %>
        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <% if @project.initiating? %>
              <ul class="options">
                <li class="option" ng-class="{ selected: project.durationType == 'duration' }">
                  <span class="select">
                    <input type="radio" ng-model="project.durationType" id="duration_duration" value="duration"/>
                    <label for="duration_duration">Tổng thời gian (ngày)</label>
                  </span>
                  <span class="value">
                    <input type="text" name="duration" ng-model="project.duration" ng-auto-numeric="days" class="form-control"/>
                  </span>
                </li>
                <li class="option" ng-class="{ selected: project.durationType == 'deadline' }">
                  <span class="select">
                    <input type="radio" ng-model="project.durationType" id="duration_deadline" value="deadline"/>
                    <label for="duration_deadline">Ngày kết thúc</label>
                  </span>
                  <span class="value">
                    <ng-datetime-picker ng-model="project.deadline" language="en" date-format="DD-MM-YYYY"/>
                  </span>
                </li>
              </ul>
          <% else %>
              <strong>
                Kết thúc vào <b></b>. Tổng thời gian gây vốn là <b><%= @project.duration %></b> ngày
              </strong>
          <% end %>
        </div>
      </div>
      <div class='form-element'>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <%= f.label t('project.edit.basic.funding_goal') %><br/>

        </div>

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <% if @project.initiating? %>
              <input type="text" ng-model="project.fundingGoal" ng-auto-numeric="currency" class="form-control"/>
          <% else %>
              <strong ng-bind="project.fundingGoal | money"></strong>
          <% end %>
          <p class="help">
            Mục tiêu huy động vốn là con số tối thiểu cần để bạn có thể hoàn thành dự án của mình. Nên nhớ việc huy động
            vốn chỉ có thể thành công nếu
            đạt được mục tiêu này, bạn hoàn toàn có nhận được nhiều hơn con số này như không thể ít hơn.
          </p>

          <p class="help">
            Một khi dự án của bạn đã được khởi động, bạn không thể thay đổi mục tiêu huy động vốn.
          </p>
        </div>
      </div>
      <div class="buttons-container text-right">
        <button type="button" class="btn btn-green" ng-click="saveProject()">Lưu thay đổi</button>
      </div>

  <% end %>

</div>

app/views/projects/shared/_edit_rewards.html.erb
<div>
  <div class="section-guide">
    <h2>Phần thưởng</h2>
    <p>
      Khi tham gia đóng góp cho dự án, sẽ tuyệt vời hơn nếu người góp vốn nhận lại được một điều gì đó. Bạn có thể tri ân họ bằng những phần thưởng, những món quà. Hãy thể hiện sự sáng tạo của bạn
    </p>
  </div>
  <button type="button" ng-click="showCreateReward()" class="btn btn-lg btn-info" toggle="modal">Tạo phần thưởng</button>
  <div class="row">
    <div class="rewards">
      <div ng-repeat="reward in rewards | orderBy: minimumPledgeAmount" class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <div class="reward">
          <a class="btn btn-danger pull-right" ng-click="deleteReward(reward, $index)"><i class="fa fa-times"></i></a>
          <a class="btn btn-info pull-right" ng-click="setReward(reward, $index)"><i class="fa fa-pencil"></i></a>
          <h3><b ng-bind="reward.minimumPledgeAmount | money" ng-currency></b></h3>
          <p ng-bind="reward.description"></p>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/projects/shared/_edit_story.html.erb
<div>
  <div class="section-guide">
    <h2>Câu chuyện</h2>
    <p>
      Kể cho mọi người câu chuyện đằng sau dự án của bạn, những điều thôi thúc bạn thực hiện dự án này, những khó khăn và thách thức bạn gặp phải.
    </p>
  </div>

  <button type="button" ng-click="showCreatePost()" class="btn btn-lg btn-info" toggle="modal">Tạo câu chuyện</button>
  <div class="story-posts">
    <div ng-repeat="post in posts" class="post">

      <a href="javascript:void(0);" ng-click="deletePost(post, $index)" class="btn btn-danger pull-right"><i class="fa fa-times"></i></a>
      <a class="btn btn-info pull-right" ng-click="setPost(post, $index)"><i class="fa fa-pencil"></i></a>
      <h3 ng-bind="post.title"></h3>

      <div class="image-container">
        <img ng-src="{{post.imageUrl}}" ng-title="{{post.title}}" />
      </div>
      <p ng-bind="post.body"></p>
    </div>
  </div>


</div>

app/views/projects/shared/_modal_add_reward.html.erb
<div class="modal" id='modal_add_reward' data-remodal-id="modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 class="modal-title">Thêm phần thưởng</h3>
      </div>
      <div class="modal-body clearfix">
        <div ng-show="reward.errors.length > 0" ng-cloak class="errors alert alert-danger alert-dismissible" role="alert">
          Có lỗi xảy ra khi lưu:
          <ul>
            <li ng-repeat="error in reward.errors" ng-bind="error"></li>
          </ul>
        </div>
        <div class="form-element">
          <div class="col-xs-4 col-sm-4 col-md-3 col-lg-3">
            <span>Khoản góp yêu cầu</span>
          </div>
          <div class="col-xs-8 col-sm-8 col-md-9 col-lg-9">
            <input type="text" ng-model="reward.minimumPledgeAmount" ng-auto-numeric="currency" class="form-control" rows="4"/>
            <br>
          </div>
        </div>
        <div class="form-element">
          <div class="col-xs-4 col-sm-4 col-md-3 col-lg-3">
            <span>Mổ tả</span>
          </div>
          <div class="col-xs-8 col-sm-8 col-md-9 col-lg-9">
            <div class="limit-characters">
              <textarea ng-model="reward.description" ng-trim="false" class="form-control" maxlength="{{rewardDescriptionMaxLength}}" rows="5"></textarea>

              <p ng-bind="rewardDescriptionMaxLength - reward.description.length + '/' + rewardDescriptionMaxLength"></p>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
        <button type="button" ng-click="saveReward()" class="btn btn-primary">Lưu</button>
      </div>

    </div>
  </div>
</div>

app/views/projects/shared/_modal_send_message.html.erb
<div class="modal fade" id='send-message' data-remodal-id="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for :message, url: messages_path do |f| %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h3 class="modal-title">Gửi tin nhắn cho <%= @project.user.name %></h3>
          </div>
          <div class="modal-body clearfix">
            <div class="errors alert alert-danger alert-dismissible" role="alert">
              Có lỗi xảy ra khi gửi tin nhắn
              <ul></ul>
            </div>
            <div class="alert alert-success">
              Tin nhắn của bạn đã được gửi tới <%= @project.user.name %>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <label>Nội dung</label>
              <%= f.hidden_field :receiver_id, :value => @project.user.id %>
              <%= f.text_area :body, class: 'form-control', :rows => "5" %>
              <br>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            <button type="submit" class="btn btn-primary">Gửi tin nhắn</button>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/shared/_modal_view_story.erb
<div class="modal fade" id="view-story">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/projects/shared/_show_comments.html.erb
<div id="show_comments">
  <ul class="comments">
    <% @project.comments.each do |comment| %>
        <li class="comment">
          <div class="comment-content">
            <div class="user-avatar">
             <%= image_tag (comment.user.avatar.url(:thumbnail)), class: "circle", height: "80" %>
            </div>

            <div class="comment-details">
              <div>
                <span class="user-name"><%= comment.user.name %></span>
                <span class="comment-date">cách đây <%= time_ago_in_words(comment.created_at) %></span>
              </div>
              <div class="comment-body">
                <%= comment.body %>
              </div>
            </div>
          </div>

        </li>
    <% end %>
  </ul>

  <h3>Bình luận</h3>
  <%= form_for([@project, @project.comments.build], url: project_comments_path(@project.id)) do |f| %>
      <p>
        <%= f.text_area :body, class: 'form-control' %>
      </p>

      <p>
        <%= f.submit 'Gửi bình luận', class: 'btn btn-primary', type: 'button', id: 'add_comment' %>
      </p>
  <% end %>
</div>