config/routes.rb
Rails.application.routes.draw do

  get 'pledges/create'
  get 'messages/create'

  devise_for :users do

  end

  resources :users, except: :show do

  end

  get 'profile/projects', to: 'projects#my'
  get 'profile/messages', to: 'messages#my'

  post 'profile/avatar', to: 'api/users#upload_avatar'

  get 'profile', to: 'users#show'
  get 'profile/edit', to: 'users#edit'
  get 'profile/:id', to: 'users#show', as: 'user_profile'
  put 'profile', to: 'users#update_profile'

  resources :messages do

  end

  get 'discover', to: 'discover#index'
  get 'discover/categories/:id', to: 'discover#category_projects', as: 'discover_category'

  resources :projects do

    collection do
      get 'create'
      get 'search'
    end

    resources :posts do

    end

    resources :rewards do

    end

    resources :pledges do

    end

    resources :comments do

    end

    member do

    end
  end

  get 'home/index'
  get 'home/about'
  # You can have the root of your site routed with "root"
  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  namespace :api do
    resources :projects do

      member do
        post :avatar, to: 'projects#upload_avatar', as: 'avatar'
      end

      resources :posts do

      end

      resources :rewards do

      end
    end

    post 'projects/:id' => 'projects#execute'

    resources :users do

    end


  end
end

app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :avatar, UserAvatarUploader

  validates_presence_of :name

  validates_length_of :biology, maximum: 225

  has_many :projects, :foreign_key => :creator_id
  has_many :comments, :foreign_key => :commenter_id
  has_many :sent_messages, :class_name => 'Message', :foreign_key => 'sender_id'
  has_many :received_messages, :class_name => 'Message', :foreign_key => 'receiver_id'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  skip_before_filter :verify_authenticity_token, :only => [:update, :upload_avatar]

  def update

    if current_user.id != params[:id]

    end

    user = User.find(params[:id])

    user.assign_attributes(update_user_params)

    if user.save
      render json: { :user => user }
    else
      render json: { :user => user.as_json.merge({ :errors => user.errors.full_messages }) }, :status => 200
    end
  end

  def upload_avatar
    user = current_user

    if user.update_attributes(:avatar => params[:user][:avatar])
      render json: { :image_url => user.avatar_url(:standard) }
    else
      render json: { :errors => user.errors }
    end

  end

  private
    def update_user_params
      json_params = ActionController::Parameters.new( JSON.parse(request.body.read) )
      json_params.require(:user).permit(:name, :biology, :location, :website)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    if (params[:id])
      @user = User.find(params[:id])
    else
      @user = current_user
    end

  end

  def edit
    user = current_user
  end

  def update_profile
    user = current_user
    if user.update(update_profile_params)
      render json: { :success => true, :user => user }
    else
      render json: { :success => false, :user => user.errors.values }
    end

  end

  private
    def update_profile_params
      params.require(:user).permit(:name, :biology, :location, :website)
    end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
	<%= link_to "Log in", new_session_path(resource_name) %>
</div>
  
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
  <%= link_to capitalize_first_word_letter(t :sign_up), new_registration_path(resource_name) %>
  </div>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
  <%= link_to capitalize_first_word_letter(t :forgot_password), new_password_path(resource_name) %>
  </div>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
  </div>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
  </div>
<% end -%>

<%- if devise_mapping.omniauthable? %>
<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
  </div>
<% end -%>