config/routes.rb
Rails.application.routes.draw do

  get 'pledges/create'
  get 'messages/create'

  devise_for :users do

  end

  resources :users, except: :show do

  end

  get 'profile/projects', to: 'projects#my'
  get 'profile/messages', to: 'messages#my'

  post 'profile/avatar', to: 'api/users#upload_avatar'

  get 'profile', to: 'users#show'
  get 'profile/edit', to: 'users#edit'
  get 'profile/:id', to: 'users#show', as: 'user_profile'
  put 'profile', to: 'users#update_profile'

  resources :messages do

  end

  get 'discover', to: 'discover#index'
  get 'discover/categories/:id', to: 'discover#category_projects', as: 'discover_category'

  resources :projects do

    collection do
      get 'create'
      get 'search'
    end

    resources :posts do

    end

    resources :rewards do

    end

    resources :pledges do

    end

    resources :comments do

    end

    member do

    end
  end

  get 'home/index'
  get 'home/about'
  # You can have the root of your site routed with "root"
  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  namespace :api do
    resources :projects do

      member do
        post :avatar, to: 'projects#upload_avatar', as: 'avatar'
      end

      resources :posts do

      end

      resources :rewards do

      end
    end

    post 'projects/:id' => 'projects#execute'

    resources :users do

    end


  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, :use => :slugged

  has_many :projects, :foreign_key => :category_id

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :vietnamese).to_s
  end
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :project, :class_name => "Project", :foreign_key => :project_id
  belongs_to :user, :class_name => "User", :foreign_key => :commenter_id
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => "User", :foreign_key => :sender_id
  belongs_to :receiver, :class_name => "User", :foreign_key => :receiver_id

  validates_presence_of :body
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base

  belongs_to :user, :class_name => "User", :foreign_key => :pledger_id
  belongs_to :project, :class_name => "Project", :foreign_key => :project_id
  belongs_to :reward, :class_name => "Reward", :foreign_key => :reward_id

  validates_presence_of :pledge_amount
  
end

app/models/post.rb
class Post < ActiveRecord::Base

  mount_uploader :image, PostImageUploader

  belongs_to :project

  validates_presence_of :title
  validates_presence_of :body
  validates_length_of :body, maximum: 500

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId

  mount_uploader :image, ProjectImageUploader

  enum duration_type: { :duration => 0, :deadline => 1 }

  before_validation(on: [:create, :update]) do
    self.title = self.title.strip if attribute_present?("title")
    self.short_description = self.short_description.strip if attribute_present?("short_description")

    if attribute_present?("deadline")
      self.deadline = self.deadline.change(hour: 23, min: 59, sec: 59)
    end

  end

  friendly_id :title, :use => :slugged

  belongs_to :user, :class_name => "User", :foreign_key => :creator_id, :autosave => false
  belongs_to :category, :class_name => "Category", :foreign_key => :category_id

  has_many :comments
  has_many :pledges
  has_many :posts
  has_many :rewards

  validates_presence_of :title, :location, :slug
  validates_length_of :short_description, maximum: 200
  validates_numericality_of :funding_goal, minimum: 0

  # Overrides
  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :vietnamese).to_s
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def unsuccessful?
    ended? && total_pledge_amount < funding_goal
  end

  def ended?
    launched? && !stopped? && deadline <= Time.zone.now
  end

  def funding?
    launched? && !stopped? && deadline > Time.zone.now
  end

  def total_pledge_amount
    pledges.sum(:pledge_amount)
  end

  def remaining_days
    [(deadline - Time.zone.now).to_i / 1.day, 0].max
  end

  def has_video?
    return false
  end

  def launched?
    launched_at != nil
  end

  def stopped?
    stopped_at != nil
  end

  def deleted?
    deleted_at != nil
  end

  def initiating?
    !launched? && !stopped? && !deleted?
  end





end

app/models/reward.rb
class Reward < ActiveRecord::Base

  validates_numericality_of :minimum_pledge_amount, greater_than_or_equal_to: 1000
  validates_presence_of :description
  validates_length_of :description, maximum: 225

  belongs_to :project, :class_name => "Project", :foreign_key => :project_id

end

app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :avatar, UserAvatarUploader

  validates_presence_of :name

  validates_length_of :biology, maximum: 225

  has_many :projects, :foreign_key => :creator_id
  has_many :comments, :foreign_key => :commenter_id
  has_many :sent_messages, :class_name => 'Message', :foreign_key => 'sender_id'
  has_many :received_messages, :class_name => 'Message', :foreign_key => 'receiver_id'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

end

app/models/video.rb
class Video < ActiveRecord::Base

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discover_helper.rb
module DiscoverHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def cache_key_for_project(project)
    "projects/#{project.id}-#{project.updated_at}"
  end

  def cache_key_for_project_posts(project)
    "projects/#{project.id}/posts/all"
  end

  def cache_key_for_project_rewards(project)
    "projects/#{project.id}/rewards/all"
  end

end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/shared/_menu.html.erb
<header id="header">
  <div class="top-bar">
    <div class="slidedown collapse in" aria-expanded="true">
      <div class="container">
        <div class="phone-email pull-left">
          <a><i class="fa fa-phone"></i> Liên hệ chúng tôi : +84 (0) 98 339 0696</a>
          <a href="support@fifothemes.com"><i class="fa fa-envelope"></i> Email : info@vnstarter.vn

          </a>
        </div>
        <div class="follow-us pull-right">
          <ul class="social pull-left">
            <li class="facebook"><a style="cursor: pointer;"><i class="fa fa-facebook"></i></a></li>
            <li class="linkedin"><a style="cursor: pointer;"><i class="fa fa-linkedin"></i></a></li>
            <li class="rss"><a style="cursor: pointer;"><i class="fa fa-rss"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="main-bar">
    <div class="container">

      <div class="row header">
        <div class="col-xs-3 col-sm-3 col-md-2 col-lg-2 logo">
          <h1>
            <a href="/">
              <img src="/images/logo.png" alt="VnStarter" width="125">
            </a>
          </h1>
        </div>

        <div class="col-xs-9 col-sm-9 col-md-10 col-lg-10">

          <!-- Left hand side navigation -->
          <nav class="menu pull-left">
            <ul>
              <li>
                <a href="/projects/new">Huy động vốn</a>
              </li>
              <li>
                <a href="/discover">Góp vốn</a>
              </li>
            </ul>
          </nav>

          <!-- Right hand side navigation -->
          <nav class="menu pull-right">
            <ul class="user-menu navigation">
              <% if (!user_signed_in?) %>
                  <li>
                    <a href="/users/sign_up">Đăng ký</a>
                  </li>
                  <li>
                    <a href="/users/sign_in">Đăng nhập</a>
                  </li>
              <% else %>
                  <li class="has-user">
                    <%= hidden_field_tag :user_name, current_user.name %>
                    <%= hidden_field_tag :user_image_url, "/images/no-image-user.png" %>
                    <a>
                      <%= image_tag current_user.avatar_url(:thumbnail), class: "circle" %>
                      <span class="sf-sub-indicator"><i class="fa fa-angle-down "></i>
                    </span>
                    </a>

                    <div class="user-dropdown">
                      <div class="user-menu-header">
                        <h5><%= current_user.name %></h5>
                      </div>
                      <ul class="options">
                        <li>
                          <label><%= link_to "Dự án đã tạo", profile_projects_path %></label>
                        </li>
                        <li>
                          <label><%= link_to "Tin nhắn", profile_messages_path %></label>
                        </li>
                        <li>
                          <label><%= link_to "Thông tin cá nhân", profile_path %></label>
                        </li>
                        <li>
                          <label><%= link_to "Đăng xuất", destroy_user_session_path %></label>
                        </li>
                      </ul>
                    </div>
                  </li>
              <% end %>
            </ul>
          </nav>

        </div>
      </div>
    </div>
  </div>
</header>