config/routes.rb
Rails.application.routes.draw do

  get 'pledges/create'
  get 'messages/create'

  devise_for :users do

  end

  resources :users, except: :show do

  end

  get 'profile/projects', to: 'projects#my'
  get 'profile/messages', to: 'messages#my'

  post 'profile/avatar', to: 'api/users#upload_avatar'

  get 'profile', to: 'users#show'
  get 'profile/edit', to: 'users#edit'
  get 'profile/:id', to: 'users#show', as: 'user_profile'
  put 'profile', to: 'users#update_profile'

  resources :messages do

  end

  get 'discover', to: 'discover#index'
  get 'discover/categories/:id', to: 'discover#category_projects', as: 'discover_category'

  resources :projects do

    collection do
      get 'create'
      get 'search'
    end

    resources :posts do

    end

    resources :rewards do

    end

    resources :pledges do

    end

    resources :comments do

    end

    member do

    end
  end

  get 'home/index'
  get 'home/about'
  # You can have the root of your site routed with "root"
  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  namespace :api do
    resources :projects do

      member do
        post :avatar, to: 'projects#upload_avatar', as: 'avatar'
      end

      resources :posts do

      end

      resources :rewards do

      end
    end

    post 'projects/:id' => 'projects#execute'

    resources :users do

    end


  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId

  mount_uploader :image, ProjectImageUploader

  enum duration_type: { :duration => 0, :deadline => 1 }

  before_validation(on: [:create, :update]) do
    self.title = self.title.strip if attribute_present?("title")
    self.short_description = self.short_description.strip if attribute_present?("short_description")

    if attribute_present?("deadline")
      self.deadline = self.deadline.change(hour: 23, min: 59, sec: 59)
    end

  end

  friendly_id :title, :use => :slugged

  belongs_to :user, :class_name => "User", :foreign_key => :creator_id, :autosave => false
  belongs_to :category, :class_name => "Category", :foreign_key => :category_id

  has_many :comments
  has_many :pledges
  has_many :posts
  has_many :rewards

  validates_presence_of :title, :location, :slug
  validates_length_of :short_description, maximum: 200
  validates_numericality_of :funding_goal, minimum: 0

  # Overrides
  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :vietnamese).to_s
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def unsuccessful?
    ended? && total_pledge_amount < funding_goal
  end

  def ended?
    launched? && !stopped? && deadline <= Time.zone.now
  end

  def funding?
    launched? && !stopped? && deadline > Time.zone.now
  end

  def total_pledge_amount
    pledges.sum(:pledge_amount)
  end

  def remaining_days
    [(deadline - Time.zone.now).to_i / 1.day, 0].max
  end

  def has_video?
    return false
  end

  def launched?
    launched_at != nil
  end

  def stopped?
    stopped_at != nil
  end

  def deleted?
    deleted_at != nil
  end

  def initiating?
    !launched? && !stopped? && !deleted?
  end





end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController

  skip_before_filter :verify_authenticity_token, :only => [:update, :execute, :upload_avatar]

  respond_to :json, :except => [:upload_avatar]
  respond_to :html, :only => [:upload_avatar]

  def index
    projects = Project.all
    respond_with projects
  end

  def show
    project = Project.find(params[:id])
    respond_with project
  end

  def update
    project = Project.find(params[:id])
    user = current_user

    params = project.launched ? launched_project_params : project_params

    project.assign_attributes(params)
    user.assign_attributes(project_user_params[:user])

    begin
      project.transaction do
        project.save!
        user.save!
      end
      render json: {:project => project.as_json.merge({ :user => user.as_json(:only => [:email, :id, :name, :biology, :location, :website]).merge({:image_url => user.avatar_url(:standard)}),})}
    rescue ActiveRecord::RecordInvalid => exception
      render json: {:project => project.as_json.merge({ :user => user.as_json(:only => [:email, :id, :name, :biology, :location, :website]).merge({:image_url => user.avatar_url(:standard), :errors => user.errors}),
                                                        :errors => project.errors })}, :status => 200
    end
  end

  def execute
    project = Project.find(params[:id])
    operation = params[:operation]

    case operation
      when "launch"
        launch_project(project)
      when "stop"
        stop_project(project)
      else

    end
  end

  def upload_avatar
    project = Project.find(params[:id])
    
    if project.update_attributes(:image => params[:project][:image])
      render json: { :image_url => project.image_url(:medium) }
    else
      render json: { :errors => project.errors }
    end
  end

  protected
  def launch_project(project)

    if project.deleted? || project.launched? || project.stopped?
      render json: {:project => project}
    end

    current_time = Time.zone.now

    if project.duration_type == "duration"
      duration = project.duration
      deadline = current_time + duration.days
    else
      deadline = project.deadline
      duration = (deadline - current_time).to_i / 1.day
    end

    deadline = deadline.change(hour: 23, min: 59, sec: 59)

    if project.update_attributes(
        :launched => true,
        :launched_at => current_time,
        :deadline => deadline,
        :duration => duration
    )
      render json: { :project => project }
    else
      render json: { :project => project.as_json.merge({:errors => project.errors}) }
    end
  end

  def stop_project(project)

  end

  private
  def project_params
    json_params = ActionController::Parameters.new(JSON.parse(request.body.read))
    json_params.require(:project).permit(:title, :location, :category_id, :short_description, :funding_goal, :duration_type, :duration, :deadline, :image)
  end

  def project_user_params
    json_params = ActionController::Parameters.new(JSON.parse(request.body.read))
    json_params.require(:project).permit(:user => [:name, :biology, :location, :website])
  end

  def launched_project_params
    json_params = ActionController::Parameters.new(JSON.parse(request.body.read))
    json_params.require(:project).permit(:title, :location, :category_id, :short_description, :image, :user)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show, :new]
  skip_before_filter :verify_authenticity_token, :only => [:upload_image]


  def index
    @projects = Project.where(launched_at: nil, deleted_at: nil, stopped_at: nil)


  end

  def about

  end

  def my
    @projects = Project.where(user: current_user)
  end

  def search
    search_key = params[:search_key]

  end

  def show
    @project = Project.includes(:user).friendly.find(params[:id])

    if @project.deleted? || (!my_project?(@project) && @project.initiating?)
      redirect_to root_path

    else
      @pledges = @project.pledges

      render 'show'
    end

  end

  def share



  end

  def new
    @cities = City.all

    @categories = Category.all

    @project = Project.new()

  end

  #View to create a new projects
  def create
    project = Project.new(project_params)
    user = current_user
    project.creator_id = user.id
    project.funding_goal = 1000000
    project.duration = 10

    if project.save
      redirect_to edit_project_path(project.id)
    else
      @cities = City.all
      @categories = Category.all
      @project = project
      @project.category_id = params[:project][:category_id]
      @project.location = params[:project][:location]
      render 'new'
    end
  end

  #View to edit an existing projects
  def edit
    @cities = Rails.cache.fetch("cities/all", expires_in: 30.days) do
        City.all
    end

    project = Project.find(params[:id])

    if project.deleted? || !my_project?(project)
      redirect_to root_path
    end

    if project.duration_type == "duration"
      project.deadline = Time.zone.now
      project.duration = project.duration || 1
    else
      project.duration = 0
    end

    gon.project = project.as_json.merge(
        {
            :image_url => project.image_url(:medium),
            :project_image_upload_url => avatar_api_project_path(project.id),
            :deadline => project.deadline.strftime("%d-%m-%Y"),
            :user => project.user.as_json(:only => [:email, :id, :name, :biology, :location, :website]).merge(
                {
                    :image_url => project.user.avatar_url(:standard),
                    :user_avatar_upload_url => "/profile/avatar"
                }),
            :rewards => Rails.cache.fetch("projects/#{project.id}/rewards/all", expires_in: 30.days) do
              Reward.where("project_id = :project_id", { project_id: project.id }).map { |reward| reward.as_json }
            end,
            :posts => Rails.cache.fetch("projects/#{project.id}/posts/all", expires_in: 30.days) do
              Post.where("project_id = :project_id", { project_id: project.id }).map { |post| post.as_json.merge({:image_url => post.image_url(:medium)}) }
            end
        }
    )

    @project = project
  end

  def stop_project

    project = Project.find(params[:id])

    render json: {:success => false} if project.deleted?
    render json: {:success => false} if !project.launched?
    render json: {:success => false} if project.stopped?

    if project.update_attributes(:stopped_at => Time.zone.now)
      render json: {:success => true}
    else
      render json: {:success => false, :errors => project.errors}
    end

  end

  private
    def my_project?(project)
      return current_user && project.creator_id == current_user.id
    end

    def project_params
      params.require(:project).permit(:title, :location, :category_id, :short_description, :funding_goal, :duration_type, :duration, :deadline)
    end

    def launched_project_params
      params.require(:project).permit(:title, :location, :category_id, :short_description)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def cache_key_for_project(project)
    "projects/#{project.id}-#{project.updated_at}"
  end

  def cache_key_for_project_posts(project)
    "projects/#{project.id}/posts/all"
  end

  def cache_key_for_project_rewards(project)
    "projects/#{project.id}/rewards/all"
  end

end

app/views/projects/edit.html.erb
<% page_title t('text.edit_your_project') %>
<% body_id "project_edit" %>

<div ng-controller="ProjectEditCtrl">
  <div class="content-wrapper">
    <div class="body-wrapper">
      <div class="container">
        <div class="row">
          <form name="projectForm">
              <div class="content-head text-center">
                <div class="container">
                  <%= hidden_field_tag :project_id, @project.id %>
                  <%= hidden_field_tag :project_slug, @project.slug %>
                  <h2><%= @project.title %></h2>
                </div>
              </div>

              <div id="message_container">
                <div class="container">
                  <div class="alert alert-success" ng-bind="successMessage" ng-show="successMessage != null" ng-cloak>
                  </div>
                  <div class="alert alert-danger" ng-show="showErrorMessage" ng-cloak>
                    <ul class=""></ul>
                  </div>
                </div>
              </div>

              <div class="tab-container clearfix">
                <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                  <div class="affix-container" data-spy="affix" data-offset-top="260">
                    <ul id="edit_tabs" class="etabs clearfix">
                      <li class="tab first active" role="presentation">
                        <a href="#basic" data-edit-info="basic" aria-controls="home" role="tab" data-toggle="tab">
                          <i class="number">1</i> Thông tin cơ bản
                        </a>
                      </li>

                      <li class="tab" role="presentation">
                        <a href="#story" data-edit-info="story" aria-controls="home" role="tab" data-toggle="tab">
                          <i class="number">2</i> Câu chuyện
                        </a>
                      </li>

                      <li class="tab" role="presentation">
                        <a href="#rewards" data-edit-info="rewards" aria-controls="home" role="tab" data-toggle="tab">
                          <i class="number">3</i> Phần thưởng
                        </a>
                      </li>

                      <li class="tab last" role="presentation">
                        <a href="#about_you" data-edit-info="profile" aria-controls="home" role="tab" data-toggle="tab">
                          <i class="number">4</i> Thông tin cá nhân
                        </a>
                      </li>

                      <li class="tab hidden" role="presentation">
                        <a href="#accounts" data-edit-info="accounts" aria-controls="home" role="tab" data-toggle="tab">
                          <i class="number">5</i> Tài khoản
                        </a>
                      </li>
                    </ul>
                    <% if !@project.launched? && !@project.stopped? && !@project.deleted? %>
                        <a ng-click="showLaunchProject()" class="btn btn-lg btn-primary" href="javascript:void(0);">Khởi động dự án</a>
                    <% end %>
                    <div class="save-container">
                      <%= link_to "Xem dự án", project_path(@project), class: "btn btn-lg btn-grey"  %>
                      <a href="javascript:void(0);" ng-click="saveProject()" ng-class="{'disabled': projectForm.$pristine}" ng-cloak class="btn btn-lg btn-primary">
                        <span ng-show="projectForm.$pristine">Đã lưu</span>
                        <span ng-show="projectForm.$dirty && !savingProject">Lưu thay đổi</span>
                        <span ng-show="projectForm.$dirty && savingProject">Đang lưu...</span>
                      </a>
                      <p ng-show="projectForm.$dirty">Bạn có thay đổi chưa được lưu</p>
                    </div>
                  </div>
                </div>
                <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
                  <div class="tabs-content">
                    <div id="basic" role="tabpanel" class="active">
                      <%= render "projects/shared/edit_basic" %>
                    </div>
                    <div id="rewards" role="tabpanel">
                      <%= render "projects/shared/edit_rewards" %>
                    </div>
                    <div id="story" role="tabpanel">
                      <%= render "projects/shared/edit_story" %>
                    </div>
                    <div id="about_you" role="tabpanel">
                      <%= render "projects/shared/edit_about_you" %>
                    </div>

                    <div id="accounts" role="tabpanel">
                      <%= render "projects/shared/edit_accounts" %>
                    </div>
                  </div>
                </div>
              </div>
              <a href="#header" class="smoothScroll" id="go_top"></a>
          </form>
        </div>
      </div>
    </div>

    <div class="modal_dialog spinning" ng-cloak ng-show="showSpinner">
      <div class="modal_dialog_outer">
        <div class="modal_dialog_sizer">
          <div class="modal_dialog_inner">
            <div class="modal_dialog_content"></div>
          </div>
          <span class="modal_dialog_ie_hack"></span>
        </div>
      </div>
    </div>

    <%= render "projects/shared/modal_add_reward" %>
    <%= render "projects/shared/modal_add_story_post" %>
    <%= render "projects/shared/modal_launch_project" %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="content-wrapper">
  <div class="body-wrapper">
    <h2 class="h2-section-title">Các dự án</h2>

    <div class="divider divider-shadow"></div>
    <div class="section-content section-tabs full-tabs">
      <div class="tab-container">
        <div class="section-tab-arrow"></div>
        <div class="section-etabs-container">
          <ul class="section-etabs">
            <li class="tab active">
              <a href="#tabc1"> Đời sống </a>
            </li>
            <li class="tab">
              <a href="#tabc2"> Âm nhạc </a>
            </li>
            <li class="tab">
              <a href="#tabc3"> Công nghệ </a>
            </li>
            <li class="tab">
              <a href="#tabc4"> Nhiếp ảnh </a>
            </li>
            <li class="tab">
              <a href="#tabc5"> Nhà hàng </a>
            </li>
            <li class="tab">
              <a href="#tabc6"> Cộng đồng </a>
            </li>
            <li class="tab">
              <a href="#tabc7"> Môi trường </a>
            </li>
            <li class="tab">
              <a href="#tabc8"> Du lịch </a>
            </li>
            <li class="tab">
              <a href="#tabc9"> Bảo tàng </a>
            </li>
          </ul>
        </div>

        <div class="tab-content">

          <div id="tabc1">
            <div class="section-content ">
              <div class="container">

                <div class="container">
                  <div class="row">
                    <div class="row">
                      <% @projects.each do |project| %>

                          <div class="col-md-3 col-sm-3">
                            <div class="feature animated" data-animtype="fadeInUp" data-animrepeat="0" data-animspeed="1s" data-animdelay="0.4s">
                              <div class="feature-image img-overlay">
                                <% if project.image.exists? %>
                                    <%= image_tag project.image.url %>
                                <% end %>
                              </div>

                              <div class="feature-content">
                                <h3 class="h3-body-title blog-title">
                                  <%= link_to(project) do %>
                                      <%= project.title %>
                                  <% end %>
                                </h3>

                                <p>
                                  <%= project.short_description %>
                                </p>

                                <p><span class="fa fa-map-marker"></span>&nbsp; <%= project.location %></p>

                                <div class="progress">
                                  <div class="progress-bar animated" role="progressbar" aria-valuenow="2%"
                                       aria-valuemin="0" aria-valuemax="100"
                                       data-animtype="animate-progress"
                                       data-animrepeat="0">
                                  </div>
                                </div>
                                <span class="">2.5tr/200tr&nbsp;|Còn 2 ngày</span>
                              </div>

                              <div class="feature-details">
                                <i class="icon-calendar"></i>
                                <span>July 10, 2013</span>
                                <span class="details-seperator"></span>

                                <a href="#"><i class="icon-comment"></i><span>4</span></a>


                                <div class="feature-share">
                                  <a href="#"><i class="icon-heart"></i></a>
                                  <a href="#"><i class="icon-facebook"></i></a>
                                </div>
                              </div>
                            </div>
                          </div>

                      <% end %>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </div>

          <div id="tabc2"></div>

          <div id="tabc3"></div>

          <div id="tabc4"></div>

          <div id="tabc5"></div>

          <div id="tabc6"></div>

          <div id="tabc7"></div>

          <div id="tabc8"></div>

          <div id="tabc9"></div>

        </div>
      </div>
    </div>


    <div class="space-sep40"></div>

  </div>
  <!--.content-wrapper end -->

</div>

app/views/projects/my.html.erb
<% page_title "Dự án đã tạo" %>
<% body_id "projects_my" %>
<div class="content-wrapper">
  <div class="body-wrapper">
    <div class="content-head text-center">
      <div class="container">
        <h2 class="text-left"><%= current_user.name %></h2>
        <h6>&nbsp;</h6>
      </div>
    </div>
    <div class="content-nav">
      <div class="container">
        <ul class="nav nav-tabs">
          <li>
            <a href="/profile/">Thông tin cá nhân</a>
          </li>
          <li class="active">
            <%= link_to "Dự án đã tạo", profile_projects_path %>
          </li>
        </ul>
      </div>
    </div>
    <div class="content-main">
      <div class="container">

        <ul class="projects">
          <% @projects.each do |project| %>
              <li class="project clearfix">
                  <a href="" class="project-image pull-left">
                    <%= image_tag project.image_url(:small) %>
                  </a>
                <div class="project-content">
                  <div class="actions">
                    <div class="btn-group white-split-button" role="group">
                      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        Quản lý <span class="fa fa-angle-down"></span>
                      </button>
                      <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "Chỉnh sửa", edit_project_path(project.id) %></li>
                        <li><%= link_to "Theo dõi", project_path(project) %></li>
                      </ul>
                    </div>
                  </div>
                  <h3>
                    <%= link_to project.title, project_path(project) %>

                    <% if project.initiating? %>
                        <span class="annotation-pill pill-draft">Đang khởi tạo</span>
                    <% elsif project.funding? %>
                        <span class="annotation-pill pill-happy">Đã khởi động</span>
                    <% end %>
                  </h3>
                  <h5>
                    thực hiện bởi <%= link_to project.user.name, user_profile_path(project.user) %>
                  </h5>
                </div>
              </li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/projects/new.html.erb
<% page_title t('text.create_project') %>
<% body_id "project_new" %>

<div class="content-wrapper">
  <div class="body-wrapper">

    <div class="content-head text-center">
      <div class="container">
        <h2><%= t('text.create_project') %></h2>
      </div>
    </div>

    <div class="content-main">
      <div class="container">
        <div class="classic-form">
          <div class="row">
            <div class="col-md-12 col-sm-12">
              <div class="clearfix">
                <%= form_for :project, url: projects_path, method: :get do |f| %>

                    <% if @project.errors.any? %>
                        <div class="alert alert-danger">
                          <ul>
                            <% @project.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                          </ul>
                        </div>
                    <% end %>

                    <h2>
                      <div class="row">
                        <div class='col-md-4 col-sm-4'>
                          <%= f.label t("project.edit.basic.category") %><br/>
                          <%= f.select :category_id, options_from_collection_for_select(@categories, 'id', 'name', @project.category_id), {:include_blank => false}, {class: 'form-control'} %>
                        </div>
                        <div class='col-md-4 col-sm-4'>

                          <%= f.label t("project.edit.basic.project_title") %><br/>
                          <%= f.text_field :title, autofocus: true, class: 'form-control' %>
                        </div>
                        <div class='col-md-4 col-sm-4'>
                          <%= f.label t("project.edit.basic.location") %><br/>
                          <%= f.select :location, options_from_collection_for_select(@cities, 'name', 'name', @project.location), {:include_blank => false}, {class: 'form-control'} %>
                        </div>
                      </div>

                    </h2>
                    <%= f.submit "Khởi tạo", class: 'btn btn-lg btn-primary' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

</div>